# Status
STATUS_PENDING = 'Pending'
STATUS_CONFIRMED = 'Confirmed'
STATUS_INVOICE = 'Invoice'
STATUS_CLOSED = 'Closed'

# Type
INVOICE_TAX = 'Tax Invoice'
INVOICE_PROFORMA = 'Proforma Invoice'
INVOICE_TAX_EXEMPTED = 'Tax Exempted Invoice'

# Service Tax
SERVICE_TAX_PERCENTAGE = 15
GST_SERVICE_TAX_PERCENTAGE = 18
CGST_SERVICE_TAX_PERCENTAGE = 9
SGST_SERVICE_TAX_PERCENTAGE = 9

